# Generated by Django 4.2.8 on 2023-12-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RM', models.FloatField()),
                ('LSTAT', models.FloatField()),
                ('PTRATIO', models.FloatField()),
            ],
        ),
    ]
